---
- name: install basic packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
  with_items:
    - python-software-properties
    - python
    - g++
    - make
    - vim
    - htop
    - git-core

- name: install ansible dependencies
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
  with_items:
    - libpq-dev
    - python-psycopg2
