---
- name: install application server packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
  with_items:
    - supervisor

- name: install app dependencies
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
  with_items:
    - python-setuptools
    - python-dev
    - python-pip

- name: copy supervisorctl files
  template:
    src: supervisor.js
    dest: "/etc/supervisor/conf.d/{{ app }}.conf"
    owner: root
    group: root
    mode: 0600

- name: update supervisorctl
  shell: supervisorctl update

- name: allow user to use supervisorctl
  template:
    src: sudoers
    dest: "/etc/sudoers.d/{{ app }}"
    owner: root
    group: root
    mode: 0440

- name: create deployment directories
  file:
    path: "/home/{{ user }}/.sentry"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0760
    state: directory
    recurse: yes

- name: copy config files
  template:
    src: "sentry.js"
    dest: "/home/{{ user }}/.sentry/sentry.conf.py"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600

- name: install virtualenv
  pip:
    name: virtualenv

- name: install pexpect
  pip:
    name: pexpect
    virtualenv: "/home/{{ user }}/env"

- name: install sentry and plugins
  pip:
    name: "{{ item }}"
    virtualenv: "/home/{{ user }}/env"
  with_items:
    - "sentry[postgres]"
    - "sentry-github"
    - "git+https://github.com/dwaiter/django-bcrypt#egg=django-bcrypt"
    - "sentry-pivotal"
  notify:
    - restart supervisor

- name: correct folder permissions
  file:
    path: "/home/{{ user }}/env"
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes

- name: migrate database
  shell: "su {{ user }} -c 'source /home/{{ user }}/env/bin/activate && sentry --config=/home/{{ user }}/.sentry/sentry.conf.py upgrade'"

- name: copy superuser creation template
  template:
    src: "createsuperuser.js"
    dest: "/home/{{ user }}/temp.py"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: create super user
  shell: "su {{ user }} -c 'source /home/{{ user }}/env/bin/activate && python /home/{{ user }}/temp.py'"

- name: remove superuser creation template
  file:
    path: "/home/{{ user }}/temp.py"
    state: absent
