---
- name: install webserver packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
  with_items:
    - nginx-full

- name: enable gzip
  lineinfile:
    dest: /etc/nginx/nginx.conf
    state: present
    regexp: "^.*({{ item[:20] }})"
    insertafter: ^http {.*
    line: "\t{{ item }}"
  with_items:
    - gzip on;
    - gzip_http_version 1.1;
    - gzip_comp_level 2;
    - gzip_types text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript application/json;
    - gzip_disable "msie6";
  notify:
    - restart nginx

- name: create ssl dir
  file:
    dest: /etc/nginx/ssl
    owner: root
    group: root
    mode: 0600
    state: directory
  when: "'{{ protocol }}' == 'https'"

- name: copy ssl files
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/{{ app }}{{ item[-4:] }}"
    owner: root
    group: root
    mode: 0600
  when: "'{{ protocol }}' == 'https'"
  with_items:
    - ssl.crt
    - ssl.key
  notify:
    - restart nginx

- name: copy site configuration
  template:
    src: "{{ protocol }}_vhost.js"
    dest: "/etc/nginx/sites-available/{{ app }}"
    owner: root
    group: root
    mode: 0600

- name: symlink site configuration
  file:
    src: "/etc/nginx/sites-available/{{ app }}"
    dest: "/etc/nginx/sites-enabled/{{ app }}"
    owner: root
    group: root
    mode: 0644
    state: link
  notify:
    - restart nginx

- name: ensure nginx is running
  service:
    name: nginx
    state: started
