---
- name: install postgres packages
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - postgresql
    - postgresql-contrib

- name: setup database
  sudo_user: postgres
  postgresql_db: db={{ db }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'

- name: grant access for database to user
  sudo_user: postgres
  postgresql_user: db={{ db }}
                   user={{ db_user }}
                   password={{ db_password }}
                   role_attr_flags=CREATEDB,SUPERUSER
